In [ ]:
##1. Create a Three Dimensional array and perform the above operations.

In [4]:
import numpy as np
a = np.array([[[1,2,3],[4,5,6]],[[5,6,7],[8,9,0]]])
print(a)

print("size of the array is ",len(a))
print("shape of the array", a.shape)

[[[1 2 3]
  [4 5 6]]

 [[5 6 7]
  [8 9 0]]]
size of the array is  2
shape of the array (2, 2, 3)


In [5]:
a[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
a[-1]

array([[5, 6, 7],
       [8, 9, 0]])

In [7]:
a[0:5]

array([[[1, 2, 3],
        [4, 5, 6]],

       [[5, 6, 7],
        [8, 9, 0]]])

In [9]:
a[-5:]

array([[[1, 2, 3],
        [4, 5, 6]],

       [[5, 6, 7],
        [8, 9, 0]]])

In [11]:
a.max

<function ndarray.max>

In [12]:
a.min

<function ndarray.min>

In [13]:
a.mean

<function ndarray.mean>